name: Deploy

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy-test:
    if: github.ref == 'refs/heads/develop'
    runs-on: [self-hosted, linux, dev]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ----------------------
      # Кэш PHP зависимостей
      - name: Cache PHP dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: vendor-${{ hashFiles('**/composer.lock') }}

      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      # ----------------------
      # Кэш Node зависимостей
      - name: Cache Node dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Build frontend
        run: |
          npm install
          npm run build

      # ----------------------
      # Deploy code
      - name: Deploy to test
        run: |
          # Синхронизация файлов, исключая .env, storage и bootstrap/cache
          rsync -avz --exclude='.git' --exclude='.env' --exclude='storage' --exclude='bootstrap/cache' ./ /var/www/art/dev

          # Artisan команды под www-data
          sudo -u www-data php /var/www/art/dev/artisan migrate --force
          sudo -u www-data php /var/www/art/dev/artisan config:clear
          sudo -u www-data php /var/www/art/dev/artisan cache:clear

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: [self-hosted, linux, prod]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ----------------------
      # Кэш PHP зависимостей
      - name: Cache PHP dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: vendor-${{ hashFiles('**/composer.lock') }}

      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      # ----------------------
      # Кэш Node зависимостей
      - name: Cache Node dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Build frontend
        run: |
          npm install
          npm run build

      # ----------------------
      # Deploy code
      - name: Deploy to prod
        run: |
          rsync -avz --exclude='.git' --exclude='.env' --exclude='storage' --exclude='bootstrap/cache' ./ /var/www/art/prod

          sudo -u www-data php /var/www/art/prod/artisan migrate --force
          sudo -u www-data php /var/www/art/prod/artisan config:clear
          sudo -u www-data php /var/www/art/prod/artisan cache:clear

#NUDAVAI!BLYATSUKA!NAH
