name: Deploy

on:
  push:
    branches:
      - develop   # деплой на TEST
      - main      # деплой на PROD

jobs:
  deploy-test:
    if: github.ref == 'refs/heads/develop'
    runs-on: [self-hosted, linux, dev]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Build frontend
        run: |
          npm install
          npm run build

      - name: Deploy to test
        run: |
          sudo rsync -avz --exclude='.git' --delete --no-perms ./ /var/www/art/dev
          sudo chown -R www-data:www-data /var/www/art/dev
          sudo -u www-data bash -c "cd /var/www/art/dev && php artisan migrate --force && php artisan config:clear && php artisan cache:clear"

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: [self-hosted, linux, prod]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Build frontend
        run: |
          npm install
          npm run build

      - name: Deploy to prod
        run: |
          sudo rsync -avz --exclude='.git' --delete --no-perms ./ /var/www/art/prod
          sudo chown -R www-data:www-data /var/www/art/prod
          sudo -u www-data bash -c "cd /var/www/art/prod && php artisan migrate --force && php artisan config:clear && php artisan cache:clear"
