name: Deploy

on:
  push:
    branches:
      - develop   # деплой на TEST
      - main      # деплой на PROD

jobs:
  deploy-test:
    if: github.ref == 'refs/heads/develop'
    runs-on: [self-hosted, linux, dev]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Build frontend
        run: |
          npm install
          npm run build

      - name: Deploy to test
        run: |
          # Синхронизация файлов, кроме storage и bootstrap/cache
          rsync -avz --exclude='.git' --exclude='storage' --exclude='bootstrap/cache' \
            --delete ./ /var/www/art/dev
          
          # Artisan команды
          php /var/www/art/dev/artisan migrate --force
          php /var/www/art/dev/artisan config:clear
          php /var/www/art/dev/artisan cache:clear

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: [self-hosted, linux, prod]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Build frontend
        run: |
          npm install
          npm run build

      - name: Deploy to prod
        run: |
          rsync -avz --exclude='.git' --exclude='storage' --exclude='bootstrap/cache' \
            --delete ./ /var/www/art/prod
          
          php /var/www/art/prod/artisan migrate --force
          php /var/www/art/prod/artisan config:clear
          php /var/www/art/prod/artisan cache:clear
